# Generated by Django 3.2.13 on 2022-05-14 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecallToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recalled_token_hash', models.CharField(max_length=1024)),
                ('racalled_token_destroy_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.UUIDField(unique=True)),
                ('refresh_destroy_time', models.DateTimeField(default=datetime.datetime(2022, 6, 13, 22, 13, 27, 564734))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
