# Generated by Django 3.2.13 on 2022-05-14 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20220514_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='refresh_destroy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 2, 13, 31, 998787)),
        ),
    ]
