# Generated by Django 3.2.13 on 2022-05-15 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_token_refresh_destroy_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='refresh_destroy_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 10, 2, 37, 316419)),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
